apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-backend
  namespace: {{ .Values.namespace }}

  labels:
    app: employee-backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: employee-backend

  template:
    metadata:
      labels:
        app: employee-backend

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.service.port }}

          envFrom:
            - configMapRef:
                name: employee-config

            - secretRef:
                name: employee-secret

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}


          startupProbe:
            httpGet:
              path: /health
              port: 8000

            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

