apiVersion: v1
kind: Service

metadata:
  name: employee-frontend-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: employee-frontend

  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}

  type: ClusterIP
