apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: employee-ingress
  namespace: {{ .Values.namespace }}

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health

spec:
  ingressClassName: alb

  rules:
  - http:
      paths:

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: employee-backend-service
            port:
              number: 8000

      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: employee-backend-service
            port:
              number: 8000

      - path: /openapi.json
        pathType: Prefix
        backend:
          service:
            name: employee-backend-service
            port:
              number: 8000

      - path: /redoc
        pathType: Prefix
        backend:
          service:
            name: employee-backend-service
            port:
              number: 8000

      - path: /
        pathType: Prefix
        backend:
          service:
            name: employee-frontend-service
            port:
              number: 80
