apiVersion: batch/v1
kind: Job

metadata:
  name: employee-db-migration
  namespace: {{ .Values.namespace }}

spec:
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migration

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Never

          command:
            - alembic
            - upgrade
            - head

          envFrom:
            - configMapRef:
                name: employee-config

            - secretRef:
                name: employee-secret
